name: docker_build

on:
  workflow_dispatch:
  push:
    branches:
      - 'focal'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Generate tag
        id: gen_tag
        run: |
          TAG=$(printf '%(%Y%m%d%H%M%S)T\n' -1)
          echo '::set-output name=tag::'$TAG
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
              riazarbi/datasci-gui-minimal:${{ fromJson(steps.gen_tag.outputs.tag) }}
              riazarbi/datasci-gui-minimal:focal
      -
        name: Modify downstream Dockerfile
        run: |
          var="FROM riazarbi/datasci-gui-minimal:${{ fromJson(steps.gen_tag.outputs.tag) }}"
          DOWNSTREAM_REPO=datasci-r-8020
          INPUT_COMMIT_MESSAGE="Update from https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}"
          
          echo "Cloning destination git repository"
          git config --global user.email riazarbi@gmail.com
          git config --global user.name riazarbi.gh_ci
          git clone --single-branch --branch focal "https://x-access-token:${{ secrets.API_TOKEN_GITHUB }}@github.com/riazarbi/$DOWNSTREAM_REPO.git"
          cd "$DOWNSTREAM_REPO"
          echo "Changing the downstream repo FROM tag to $var"
          sed -i "1s|.*|$var|" Dockerfile
          echo "Adding git commit"
          git add -A
          git commit --message "$INPUT_COMMIT_MESSAGE"
          echo "Pushing git commit"
          git push origin 
